version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-management
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: management
    ports:
      - "3307:3306"